name: Build

on:
    push:
        branches: ["main"]
    workflow_dispatch:

jobs:
    build:
        runs-on: windows-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup .NET
              uses: actions/setup-dotnet@v4
              with:
                use-global-json: true

            - name: Build
              run: dotnet build ReenableCopilot/ReenableCopilot.csproj -c Release